Adding LastPass backend to password_fill userscript.

diff --git a/misc/userscripts/password_fill b/misc/userscripts/password_fill
--- a/misc/userscripts/password_fill
+++ b/misc/userscripts/password_fill
@@ -210,6 +210,78 @@ choose_entry_zenity_radio() {
     choose_entry_menu || true
 }
 
+# Default backend selection.
+backend="pass"
+
+# =======================================================
+# backend: LastPass. 
+# The LastPass backend depnds only on a system installation of lastpass-cli.
+# Users must define their lastpass username in password_fill_rc and set 
+# the backend variable to "last_pass"
+# e.g.
+#
+# #!/usr/bin/env bash
+# username=lp-username@email.com
+# backend=last_pass
+#
+# Temporary files are created that store account user name along
+# with the lastpass id for a given address. Users can redefine where the
+# temporary files will be saved with LP_CACHE_PREFIX the default is as such.
+#
+# No password data is ever written to a file with this method.
+
+LP_CACHE_PREFIX=$HOME/.local/share/qutebrowser/userscripts/id_cache
+
+last_pass_backend() {
+    init() {
+      PREFIX=$LP_CACHE_PREFIX
+      set +e
+
+      # Remove any old LP temporary id files.
+      for f in $PREFIX/; do
+        [ -f $f ] && rm $f 
+      done
+
+      # Check to see if the system is logged into LP else prompt
+      # the user with the LP login.
+      lpass ls
+      if ! [ $? -eq 0 ]; then
+        lpass login --trust $username
+        lpass ls
+        if [ $? -eq 0 ]; then
+          msg "Lastpass successful login."
+        else
+          die "Lastpass failed to initialize correctly."
+        fi
+      fi
+      set -e
+    }
+
+    query_entries() {
+        local url="$1"
+
+        set +e
+        lpass show $url
+        if [ $? -eq 0 ]; then
+            # Save files as usernames w/ corresponding LP id token.
+            for id in $(lpass show --id -x $url); do
+                echo "$id" > $PREFIX/$(lpass show --username -x $id)
+                files+=("$(lpass show --username -x $id)")
+            done
+        fi
+        set -e
+    }
+
+    open_entry() {
+        # Use the id tokens to pull password form the correct LP profile.
+        username="${1#* }"
+        id=$(cat $PREFIX/$username)
+        password=$(lpass show --password -x $id)
+    }
+}
+# =======================================================
+
+
 # =======================================================
 # backend: PASS
 
@@ -299,9 +371,6 @@ secret_backend() {
 }
 # =======================================================
 
-# load some sane default backend
-reset_backend
-pass_backend
 # load configuration
 QUTE_CONFIG_DIR=${QUTE_CONFIG_DIR:-${XDG_CONFIG_HOME:-$HOME/.config}/qutebrowser/}
 PWFILL_CONFIG=${PWFILL_CONFIG:-${QUTE_CONFIG_DIR}/password_fill_rc}
@@ -309,6 +378,12 @@ if [ -f "$PWFILL_CONFIG" ] ; then
     # shellcheck source=/dev/null
     source "$PWFILL_CONFIG"
 fi
+BACKEND_CLASS="$backend"_backend
+
+# load some sane default backend
+reset_backend
+$BACKEND_CLASS
+
 init
 
 simplify_url "$QUTE_URL"
